### ISSUE TITLE
[WebPush] gmp extension is not loaded but is required for sending push notifications with payload or for VAPID authentication. You can fix this in your php.ini.

### ISSUE THREAD

**Issue by Scorpions95** [lavigor/notifications#12]
![screenshot 2018-07-26 10 52 21](https://user-images.githubusercontent.com/24534657/43249080-6aa1e9f4-90c2-11e8-8c33-924f3748fbc9.png)
i have following issue when i try to post something and this appear in my forum
[https://rocknmetalbulgaria.eu](url)

**Comment by lavigor** [comment]
Please check again whether GMP extension is actually enabled in your PHP installation.

**Comment by Scorpions95** [comment]
i made  a video about it 
@lavigor 
https://youtu.be/InEdAhwB6Ts
i think it's enable it cuz las week i hadn't this problem

**Comment by Scorpions95** [comment]
The issue is fixed
The GMP is disabled cuz the migration of server of my hos
