### ISSUE TITLE
Disable initial popup?

### ISSUE THREAD

**Issue by chrisgch** [lavigor/notifications#15]
Thanks for the nice extension! Currently when a user logs in, he immediately gets a popup whether he wants to allow push notifications. Some people would find this extremely annoying.

Is there a way to disable this popup, so push notifications only get enabled when the user checks "Browser notifications: on" in the personal settings? If you don't want to make it an option, can you tell me which code I need to modify to get rid of the popup, please?

**Comment by chrisgch** [comment]
If anyone wants to do the same: I found the solution myself:
In file:
styles/all/template/js/notifications.js 
Just disable this command:
showIntroConfirmation();
by putting // in front of it:
//showIntroConfirmation();

**Comment by lavigor** [comment]
@chrisgch sorry for the late reply.
This popup is disabled by default and can be enabled in the ACP -> `Board settings` -> `Browser notifications` -> `Ask user whether he/she wants to enable Push Notifications when he/she logs in with a new browser`.
No need to make code adjustments.
