### ISSUE TITLE
 website to apk converters support

### ISSUE THREAD

**Issue by MannixMD** [lavigor/notifications#19]
Hey lavigor 
I would like to ask if it's possible to add support for push notification to work with website to apk converters like Website 2 Apk Builder?

**Comment by lavigor** [comment]
Sorry, this extension is focused only on the WebPush technology (notifications are sent directly to browsers).
Notifications from the converter you mentioned come from Firebase that is outside the scope of this extension.

**Comment by MannixMD** [comment]
Ok thanks for the quick reply :)
