### ISSUE TITLE
nothing happens.

### ISSUE THREAD

**Issue by eunaumtenhoid** [lavigor/notifications#3]
I installed, but nothing happens.
why?

**Comment by lavigor** [comment]
@eunaumtenhoid, what are you expecting to happen?

**Comment by eunaumtenhoid** [comment]
@lavigor this extension is to function as the youtube notification in the right browser?
you open the browser and it shows you a notification before you even go to youtube

**Comment by lavigor** [comment]
I don't use YouTube notifications, but it seems to be yes.
However you won't receive any Push notifications until you enable them (check out notification settings).

**Comment by eunaumtenhoid** [comment]
all activated
so tell me how it should work normally ?? What should happen?

**Comment by lavigor** [comment]
Sorry for the late reply.
Normally you should see the new `Browser notifications` switch in your notification settings and receive notifications when it is turned on.
No notifications will be sent until you enable them.

**Comment by lavigor** [comment]
It seems to me that this issue is resolved.
Please create a new issue if you still have any questions.
