### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by DigitalFuturePT** [lavigor/notifications#4]
Are you thinking on add Safari support?

There is this library:
https://github.com/jwage/php-apns

Maybe it can be easy to include it?

Good article about this:
https://medium.com/anantha-krishnan-k-g/safari-push-notifications-ec171bdf6ead

Or take a look at this: https://onesignal.com/
There is a plugin for Wordpress: https://wordpress.org/plugins/onesignal-free-web-push-notifications/

Great work! Keep it up!

**Comment by lavigor** [comment]
It seems hard to implement something that I cannot test at the moment.
As for OneSignal, it is a separate project. This extension implements WebPush support directly.

**Comment by DigitalFuturePT** [comment]
About OneSignal I know. It should be done by scratch. But for what I've checked it seems the best option to have iOS compatibility without needing to have an iOS equipment or Apple Developer account. Maybe there is a solution with some special and specific web push dunno...
Thanks for answering.
