### ISSUE TITLE
Modal Window for Accepting Notifications

### ISSUE THREAD

**Issue by DigitalFuturePT** [lavigor/notifications#5]
I know this is still beta phase but...

So I enter on the forum the modal window appears and I accept push notifications.

But then, everytime I click on Full Editor (on quick reply) and go to /posting.php?mode=reply, the modal window with the same question pop ups again 😢

**Comment by lavigor** [comment]
What browser do you use?
The modal window is supposed to be shown only once regardless of the opened page.
The state is saved in browser's localStorage.

Maybe you have an extension/script for posting page that emptys localStorage causing the described behaviour?

**Comment by TarantinoMariachi** [comment]
Yes, my quick reply extension saves text on local storage.

**Comment by TarantinoMariachi** [comment]
O use Chrome btw.

**Comment by TarantinoMariachi** [comment]
The ext I've is saving the text content in window.localStorage["TextEditorData"]

Isn't possible for you to save on a specific place inside localStorage too? And read from there like:
localStorage["PushNotifications"] or something?

**Comment by DigitalFuturePT** [comment]
Problem solved. It was in my ext. ;)
